name: Build and Upload APK

permissions:
  contents: write   # ✅ 允许创建 Release 和上传附件

on:
  push:
    tags:
      - 'v*.*.*'   # 仅当 tag 为 vX.Y.Z 格式时触发（例：v1.0.0）

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 JDK 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3️⃣ 缓存 Gradle 构建（加速）
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4️⃣ 赋予 gradlew 执行权限
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 5️⃣ 构建 Release APK
      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      # 6️⃣ 上传 APK 文件到 GitHub Artifacts（方便调试下载）
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      # 7️⃣ 自动创建 GitHub Release 并附加 APK
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
